apiVersion: apps/v1
kind: Deployment
metadata:
  name: gagan1
  namespace: gitops
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 2 
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: gitops:1.0
        ports:
        - containerPort: 8000
     